
cell_type_conv = {
    "T4_naive": "T4 Naive",
    "B_naive": "B Naive",
    "CytoT_GZMH+": "T8 GZMH",
    "T4_em": "T4 EM",
    "NK_dim": "NK Dim",
    "CytoT_GZMK+": "T8 GZMK",
    "T8_naive": "T8 Naive",
    "ncM": "nCM",
    "B_mem": "B mem",
    "T4_reg": "T4 Reg",
    "cDC": "cDC2",
    "T_mait": "T mait",
    "B_plasma": "B plasma",
    "NK_bright": "NK Bright",
    "B_atypical": "B Atypical",
    "cM": "CM",
}


# Taken directly from PopAlign and used to annotate level 1
marker_genes_1 = {
    "Monocytes": [
        "CD14",
        "CD33",
        "LYZ",
        "FCER1G",
        "LGALS3",
        "CSF1R",
        "ITGAX",
        "ITGAM",
        "CD86",
        "HLA-DRB1",
    ],
    "Dendritic cells": ["LAD1", "LAMP3", "TSPAN13", "CLIC2", "FLT3"],
    "B-cells": ["MS4A1", "CD19", "CD79A"],
    "T-helpers": ["TNF", "TNFRSF18", "IFNG", "IL2RA", "BATF"],
    "T cells": [
        "CD27",
        "CD69",
        "CD2",
        "CD3D",
        "CXCR3",
        "CCL5",
        "IL7R",
        "CXCL8",
        "GZMK",
    ],
    "Natural Killers": ["NKG7", "GNLY", "PRF1", "FCGR3A", "NCAM1", "TYROBP"],
}


# This is a list of genes which I assembled to label the second layer of cell annotation. I assembled this using several sources.
marker_genes_2 = {
    "B cells": ["PXK", "MS4A1", "CD19", "CD74", "CD79A", "BANK1", "PTPRC", "CR2"],
    "B Memory": ["NPIB15", "BACH2", "IL7", "NMBR", "MS4A1", "MBL2", "LY86", "CD27"],
    "B Naive": ["P2RX5", "SIK1", "SLC12A1", "SELL", "RALGPS2", "PTPRCAP", "PSG2"],
    "Basophils": ["CCL4", "NPL", "WRN", "NFIL3", "TEC", "OTUB2", "FAR2"],
    "cDCs": ["ITGAX", "ZBTB46", "LAMP3", "CXCR1", "ITGAM", "FCER1A", "IL6", "IRF4"],
    "Macrophages": ["CD68", "FCGR1", "NAAA", "JAML", "TYROBP", "LYZ2", "H2-DMA"],
    "Classical Monocytes": [
        "APOBEC3A",
        "LYZ",
        "CD14",
        "CFP",
        "S100A9",
        "S100A8",
        "CSF3R",
    ],
    "Intermediate Monocytes": [
        "APOBEC3A",
        "LYZ",
        "CD14",
        "CFP",
        "S100A9",
        "S100A8",
        "CSF3R",
        "CD16",
    ],
    "Myeloid DCs": [
        "CSF3R",
        "CD52",
    ],
    "Myeloid Suppressors": [
        "S100A4",
        "S100A9",
        "ICAM1",
        "S100A8",
        "ITGAM",
        "LY6G",
        "GR1",
        "FCGR3A",
    ],
    "NK": ["NKG7", "GNLY", "KLRD1", "KLRF1", "NCR1", "DOCK2", "GZMA", "IRF7"],
    "pDCs": ["BST2", "CLEC4C", "MAP3K2", "KLK1", "CMAH", "TRADD", "LILRA4", "TCF4"],
    "T Cells": ["TRBC2", "CD3D", "CD3G", "CD3E", "LTB", "IL7R", "LEF1"],
    "Cytotoxic T": ["TRAC", "CD8A", "GZMB", "CD2", "CD27", "CD5", "CD27"],
    "Helper T": ["CCR4", "CD4", "IL13", "CD28", "CD3G", "IL2", "CCR6"],
    "Memory T": ["CCR7", "CD2", "PTPRC", "CD28", "LEF1", "S100A8", "GIMAP4"],
}
